In [10]:
import pandas as pd
import numpy as np
import mord
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report

df=pd.read_csv('Dataset/winequality-red.csv',sep=';')
x=df.drop('quality',axis=1)
y=df['quality']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model = mord.LogisticAT()
model.fit(x_train,y_train)
predictions=model.predict(x_test)
conf_matrix=confusion_matrix(y_test,predictions)
class_report=classification_report(y_test,predictions,zero_division=0)
print('Confusion matrix:\n',conf_matrix)
print('Classification report:\n',class_report)

Confusion matrix:
 [[ 0  0  1  0  0  0]
 [ 0  0  9  1  0  0]
 [ 0  0 96 34  0  0]
 [ 0  0 45 81  6  0]
 [ 0  0  1 35  6  0]
 [ 0  0  0  1  4  0]]
Classification report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        10
           5       0.63      0.74      0.68       130
           6       0.53      0.61      0.57       132
           7       0.38      0.14      0.21        42
           8       0.00      0.00      0.00         5

    accuracy                           0.57       320
   macro avg       0.26      0.25      0.24       320
weighted avg       0.53      0.57      0.54       320

